# permissions for end users to view fargateprofiles.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: fargateprofile-viewer-role
rules:
- apiGroups:
  - agill.apps.eks-fargate-controller
  resources:
  - fargateprofiles
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - agill.apps.eks-fargate-controller
  resources:
  - fargateprofiles/status
  verbs:
  - get
