
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - agill.apps.agill.apps.eks-fargate-controller
  resources:
  - fargateprofiles
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - agill.apps.agill.apps.eks-fargate-controller
  resources:
  - fargateprofiles/status
  verbs:
  - get
  - patch
  - update
